---
title: "MLB Pitch Tempo"
author: 
  - "Brian Cervantes Alvarez"
  - "Cleighton Roberts"
date: "5/22/2021"
format: 
  html:
    fig-width: 8
    fig-height: 4
    code-fold: true
---

```{r}
library(tidyverse)
library(survminer)
library(survival)
library(fitdistrplus)
```


```{r}
ds <- read_csv("MLB pitch_tempo.csv")

#head(ds, 5)
#names(ds)


ds <- ds %>% rename(time = median_seconds_empty...10,
                    total_pitches = total_pitches...6) %>%
  dplyr::select(-median_seconds_empty...8,
         -entity_code, 
         -entity_id,
         -total_pitches...5)

head(ds)

```



```{r}
# Look at the distribution of the difference between hot and cold freqs
mlbds <- ds %>%
  mutate(hmc = freq_hot - freq_cold) 

mlbds %>%
  ggplot(aes(x = hmc))+
  geom_density(fill = "grey")


# Bin the temperature frequency of pitchers into "Hot", "Cold" and "Warm"
mlbds <- mlbds %>% 
  mutate(pitcher_temp = case_when(hmc > .091 ~ 'Hot',
                            hmc < (-.0486) ~ 'Cold',
                            (hmc < .091 & hmc > (-.0486)) ~ 'Warm')) %>%
  dplyr::select(time, status, pitcher_temp) 


#Survival Plot

km <- survfit(Surv(mlbds$time) ~ mlbds$pitcher_temp)

ggsurvp <- ggsurvplot(fit = km,
           data = mlbds, 
           palette = c("cyan4", "red3", "orange2"),
           risk.table = F,
           conf.int = F,
           ) + 
  labs(title='Pitch Duration',
       y = 'Percent of Pitchers',
       x ='Time to Pitch (seconds)') 

ggsurvp$plot + geom_vline(xintercept = 15)

summary(survreg(Surv(mlbds$time) ~ mlbds$pitcher_temp))

```



```{r}

survObject = Surv(ds$time, ds$status)

km <- survfit(survObject~1)

ggsurvplot(fit = km_fit,
           data = ds, 
           palette="YlOrRd",
           risk.table = F,
           conf.int=F)

```



